/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author ESFOT
 */
public class CalcularFigura extends javax.swing.JFrame {

    /**
     * Creates new form CalcularFigura
     */
    public CalcularFigura() {
        initComponents();
        txtDato1.setVisible(false);
        txtDato2.setVisible(false);
        txtDato3.setVisible(false);
        txtArea.setVisible(false);
        txtPerimetro.setVisible(false);
        lblDato1.setVisible(false);
        lblDato2.setVisible(false);
        lblDato3.setVisible(false);
        lblArea.setVisible(false);
        lblPerimetro.setVisible(false);
        btnCalcular.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbElegirFigura = new javax.swing.JComboBox<>();
        lblElegirFigura = new javax.swing.JLabel();
        lblDato1 = new javax.swing.JLabel();
        txtDato1 = new javax.swing.JTextField();
        lblDato2 = new javax.swing.JLabel();
        txtDato2 = new javax.swing.JTextField();
        lblDato3 = new javax.swing.JLabel();
        txtDato3 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        txtArea = new javax.swing.JTextField();
        txtPerimetro = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        lblPerimetro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbElegirFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Triangulo", "Cuadrado", "Rectangulo", "Circulo" }));
        cmbElegirFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbElegirFiguraActionPerformed(evt);
            }
        });

        lblElegirFigura.setText("Elegir Figura");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblArea.setText("Arrea:");

        lblPerimetro.setText("Perimetro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblElegirFigura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblDato3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCalcular))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbElegirFigura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDato1)
                            .addComponent(txtDato2)
                            .addComponent(txtDato3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblArea)
                            .addComponent(lblPerimetro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPerimetro)
                            .addComponent(txtArea, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbElegirFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElegirFigura))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDato1)
                    .addComponent(txtDato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDato2)
                    .addComponent(txtDato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDato3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerimetro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbElegirFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbElegirFiguraActionPerformed
        // TODO add your handling code here:
        String figura=cmbElegirFigura.getSelectedItem().toString();
        
       if(figura.equals("Triangulo")){
         txtDato1.setVisible(true);
        txtDato2.setVisible(true);
        txtDato3.setVisible(false);
        lblDato1.setVisible(true);
        lblDato2.setVisible(true);
        lblDato3.setVisible(false); 
        lblDato1.setText("Base:");
        lblDato2.setText("Altura:");
        btnCalcular.setVisible(true);
        txtArea.setVisible(true);
        txtPerimetro.setVisible(true);
        lblArea.setVisible(true);
        lblPerimetro.setVisible(true);
      
        
          
       }else if(figura.equals("Cuadrado")){
          txtDato1.setVisible(true);
          txtDato2.setVisible(false);
          txtDato3.setVisible(false);
          lblDato1.setVisible(true);
          lblDato2.setVisible(false);
          lblDato3.setVisible(false);
          lblDato1.setText("Lado:");
          btnCalcular.setVisible(true);
          txtArea.setVisible(true);
        txtPerimetro.setVisible(true);
        lblArea.setVisible(true);
        lblPerimetro.setVisible(true);
          
       }else if(figura.equals("Rectangulo")){
          lblDato1.setVisible(true);
          lblDato2.setVisible(true);
          lblDato3.setVisible(false);
          txtDato1.setVisible(true);
          txtDato2.setVisible(true);
          txtDato3.setVisible(false);
          lblDato1.setText("Base:");
          lblDato2.setText("Altura:");
          btnCalcular.setVisible(true);
          txtArea.setVisible(true);
        txtPerimetro.setVisible(true);
        lblArea.setVisible(true);
        lblPerimetro.setVisible(true);
          
       }else if(figura.equals("Circulo")){
          
          txtDato1.setVisible(true);
          txtDato2.setVisible(false);
          txtDato3.setVisible(false);
          lblDato1.setVisible(true);
          lblDato2.setVisible(false);
          lblDato3.setVisible(false);
          lblDato1.setText("Radio:");
          btnCalcular.setVisible(true);
          txtArea.setVisible(true);
        txtPerimetro.setVisible(true);
        lblArea.setVisible(true);
        lblPerimetro.setVisible(true);
       }
        
    }//GEN-LAST:event_cmbElegirFiguraActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        String figura=cmbElegirFigura.getSelectedItem().toString();
        double baseT=Double.valueOf(txtDato1.getText()) ;
        double alturaT=Double.valueOf(txtDato2.getText()) ;
        double ladoC=Double.valueOf(txtDato1.getText()) ;
        double baseR=Double.valueOf(txtDato1.getText()) ;
        double alturaR=Double.valueOf(txtDato2.getText()) ;
        double radio=Double.valueOf(txtDato1.getText()) ;
        Figura f;
        if(cmbElegirFigura.getSelectedItem().toString().equals("Triangulo")){

            f= new Triangulo(baseT,alturaT);
            double area=f.calcularArea();
            double p=f.calcularPerimetro();
            
            
            txtArea.setText(String.valueOf(area));
            txtPerimetro.setText(String.valueOf(p));
            txtDato1.setText("");
            txtDato2.setText("");
            txtDato3.setText("");

        }else if(figura.equals("Cuadrado")){

            f =new Cuadrado(ladoC);
            txtArea.setText(String.valueOf(f.calcularArea()));
            txtPerimetro.setText(String.valueOf(f.calcularPerimetro()));
            txtDato1.setText("");
            txtDato2.setText("");
            txtDato3.setText("");

        }else if(figura.equals("Rectangulo")){

            f =new Rectangulo(baseR,alturaR);
            txtArea.setText(String.valueOf(f.calcularArea()));
            txtPerimetro.setText(String.valueOf(f.calcularPerimetro()));
            txtDato1.setText("");
            txtDato2.setText("");
            txtDato3.setText("");
        }else if(figura.equals("Circulo")){

            f= new Circulo(radio);
            txtArea.setText(String.valueOf(f.calcularArea()));
            txtPerimetro.setText(String.valueOf(f.calcularPerimetro()));
            txtDato1.setText("");
            txtDato2.setText("");
            txtDato3.setText("");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularFigura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularFigura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbElegirFigura;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDato1;
    private javax.swing.JLabel lblDato2;
    private javax.swing.JLabel lblDato3;
    private javax.swing.JLabel lblElegirFigura;
    private javax.swing.JLabel lblPerimetro;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtDato1;
    private javax.swing.JTextField txtDato2;
    private javax.swing.JTextField txtDato3;
    private javax.swing.JTextField txtPerimetro;
    // End of variables declaration//GEN-END:variables
}
